รหัส 6610110351 ชื่อ เสฎฐวุฒิ สุภักดี Sec 07 แบบฝึกหัด Lab11



In [ ]:
#Ex.1
#สร้างอาเรย์ M ขนาด 2 มิติ ขนาด 8x8 ขึ้นมาจาก x อาเรย์ 1 มิติที่มีสมาชิก 64 ตัว
#จงเพิ่มโค้ดให้รับอินพุตเป็นจำนวนเต็มบวก 1 จำนวนจากแป้นพิมพ์แล้วเก็บใน k
#หลังจากนั้นให้เปลี่ยนค่าของช่องใน M ที่หมายเลขแถวและหลักหารด้วย k ลงตัว ให้มีค่าเป็น 0 แล้วสั่งพิมพ์ค่าอาเรย์ M ออกมา

import numpy as np
x = np.arange(64)
print('x = ',x)
M = np.array(x)
M = M.reshape(8,8)
print('M = ',M)

k = int(input('k = '))
M[::k , ::k] = 0
print(M)

x =  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
M =  [[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55]
 [56 57 58 59 60 61 62 63]]
k = 2
[[ 0  1  0  3  0  5  0  7]
 [ 8  9 10 11 12 13 14 15]
 [ 0 17  0 19  0 21  0 23]
 [24 25 26 27 28 29 30 31]
 [ 0 33  0 35  0 37  0 39]
 [40 41 42 43 44 45 46 47]
 [ 0 49  0 51  0 53  0 55]
 [56 57 58 59 60 61 62 63]]


In [ ]:
#Ex.2
#จงสร้าง P อาเรย์ 2 มิติ ชนิด int ขนาด 10x10 โดยให้สมาชิกทุกตัวมีค่าเป็น 1 โดยใช้ฟังก์ชัน
#แล้วเขียนโค้ดรับอินพุตเป็นจำนวนเต็มบวก 1 จำนวนจากแป้นพิมพ์ แล้วเก็บใน k
#หลังจากนั้นให้เปลี่ยนค่าของช่องใน P ที่หมายเลขแถวและหลักหารด้วย k ลงตัว ให้มีค่าเป็น k เท่าของค่าเดิม โดยป้อนค่า k อยู่ในช่วง 1-9
import numpy as np
P = np.ones(100, int)
P = np.array(P)
P = P.reshape(10,10)
print('P = ',P)
k = int(input('k = '))
P[::k , ::k] = k
print(P)

P =  [[1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]
k = 5
[[5 1 1 1 1 5 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [5 1 1 1 1 5 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]
 [1 1 1 1 1 1 1 1 1 1]]


In [ ]:
#Ex.3
#สร้าง M เป็นอาเรย์ 2 มิติ ชนิด float ขนาด 5x5 ด้วยฟังก์ชัน identity() และปรับค่าสมาชิกดังในโค้ด
#จงเขียนโค้ดหาค่าผลต่างของค่ามากที่สุดและค่าน้อยที่สุดในแต่ละหลัก

import numpy as np
M = np.identity(5 , float)
print(M)
M[::2 , ::3] = 8
print(M)
M[2:4 , 1:4] = [5,10,15]
print(M)
N1 = np.max(M , axis = 0)
N2 = np.min(M , axis = 0)
N = N1-N2
print(N)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[8. 0. 0. 8. 0.]
 [0. 1. 0. 0. 0.]
 [8. 0. 1. 8. 0.]
 [0. 0. 0. 1. 0.]
 [8. 0. 0. 8. 1.]]
[[ 8.  0.  0.  8.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 8.  5. 10. 15.  0.]
 [ 0.  5. 10. 15.  0.]
 [ 8.  0.  0.  8.  1.]]
[ 8.  5. 10. 15.  1.]


In [29]:
#Ex.4
#อาเรย์ X เก็บความยาวของด้านประกอบมุมฉากของรูปสามเหลี่ยมมุมฉากหลายรูป
#ให้สร้างอาเรย์ Y ซึ่งเก็บความยาวด้านตรงข้ามมุมฉาก
#แสดงผลค่าสมาชิกในอาเรย์ X และ Y
#จากนั้นให้รวมอาเรย์ X และ Y เข้าด้วยกันในอาเรย์ Z ซึ่งเก็บความยาวด้านทั้ง
#แสดงผลค่าสมาชิกในอาเรย์ Z
#แล้วเขียนอาเรย์ลงในไฟล์ไบนารี .pny ชื่อ 'ztriangles' และอ่านเก็บขึ้นมาในอาเรย์ W
#เขียนอาเรย์ W ลงในไฟล์ตัวอักษร .txt ชื่อ 'wtriangles'

import numpy as np
X = np.array([[3,4],[5,12],[24,7],[1,1]])
print(X)

Y = []
Z = []
for i in X :
  c = (i[0]**2+i[1]**2)**0.5
  Y.append(c)
  Z.append([i[0] , i[1] , c])
Y = np.array(Y)
Z = np.array(Z)
print(Y)
print(Z)

np.save('ztriangles' , np.array(Z))
W = np.load('ztriangles.npy')
np.savetxt('wtriangles.txt' , W , delimiter=' ')

[[ 3  4]
 [ 5 12]
 [24  7]
 [ 1  1]]
[ 5.         13.         25.          1.41421356]
[[ 3.          4.          5.        ]
 [ 5.         12.         13.        ]
 [24.          7.         25.        ]
 [ 1.          1.          1.41421356]]
